/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 stand.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/stand.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(()=>{
    actions.stand.play()
  })


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
          <group name="Hips" position={[0, 0.01, -1.019]} rotation={[0.032, 0, 0]}>
            <group name="LeftUpLeg" position={[0.095, -0.003, -0.005]} rotation={[3.055, -0.06, 3.069]}>
              <group name="LeftLeg" position={[0, 0, -0.458]} rotation={[-0.083, -0.006, 0]}>
                <group name="LeftFoot" position={[0, 0, -0.444]} rotation={[1.064, -0.014, -0.03]}>
                  <group name="LeftToeBase" position={[0, 0, -0.149]} rotation={[0.542, 0.059, 0.074]}>
                    <group name="LeftToe_End" position={[0, 0, -0.099]} rotation={[0, 0.03, -1.546]} />
                  </group>
                </group>
              </group>
            </group>
            <group name="RightUpLeg" position={[-0.095, -0.003, -0.005]} rotation={[3.052, 0.059, -3.065]}>
              <group name="RightLeg" position={[0, 0, -0.458]} rotation={[-0.083, 0.006, 0]}>
                <group name="RightFoot" position={[0, 0, -0.444]} rotation={[1.064, 0.014, 0.03]}>
                  <group name="RightToeBase" position={[0, 0, -0.149]} rotation={[0.542, -0.059, -0.074]}>
                    <group name="RightToe_End" position={[0, 0, -0.099]} rotation={[0, -0.03, 1.546]} />
                  </group>
                </group>
              </group>
            </group>
            <group name="Spine" position={[0, 0, -0.098]} rotation={[-0.137, 0, 0]}>
              <group name="Spine1" position={[0, 0, -0.13]} rotation={[-0.064, 0, 0]}>
                <group name="Spine2" position={[0, 0, -0.122]} rotation={[0.094, 0, 0]}>
                  <group name="LeftShoulder" position={[0.047, -0.006, -0.141]} rotation={[-2.942, -1.526, 1.771]}>
                    <group name="LeftArm" position={[0, 0, -0.119]} rotation={[0.999, -0.144, -0.019]}>
                      <group name="LeftForeArm" position={[0, 0, -0.285]} rotation={[-0.113, 0.446, -0.021]}>
                        <group name="LeftHand" position={[0, 0, -0.252]} rotation={[0.092, -0.041, -0.076]}>
                          <group name="LeftHandIndex1" position={[-0.035, -0.007, -0.097]} rotation={[0.183, 0.151, 0.09]}>
                            <group name="LeftHandIndex2" position={[0, 0, -0.045]} rotation={[0.19, 0.052, 0.007]}>
                              <group name="LeftHandIndex3" position={[0, 0, -0.028]} rotation={[0.168, -0.03, 0.155]}>
                                <group name="LeftHandIndex4" position={[0, 0, -0.034]} rotation={[0.089, -0.019, -0.113]} />
                              </group>
                            </group>
                          </group>
                          <group name="LeftHandMiddle1" position={[-0.009, -0.003, -0.1]} rotation={[0.077, 0.036, 0.134]}>
                            <group name="LeftHandMiddle2" position={[0, 0, -0.046]} rotation={[0.257, 0.088, 0.008]}>
                              <group name="LeftHandMiddle3" position={[0, 0, -0.035]} rotation={[0.408, -0.076, 0.062]}>
                                <group name="LeftHandMiddle4" position={[0, 0, -0.035]} rotation={[0.048, -0.004, -0.045]} />
                              </group>
                            </group>
                          </group>
                          <group name="LeftHandPinky1" position={[0.039, 0.011, -0.09]} rotation={[0.209, -0.296, 0.174]}>
                            <group name="LeftHandPinky2" position={[0, 0, -0.028]} rotation={[0.229, 0.169, 0.41]}>
                              <group name="LeftHandPinky3" position={[0, 0, -0.022]} rotation={[0.246, 0.027, 0.021]}>
                                <group name="LeftHandPinky4" position={[0, 0, -0.026]} rotation={[0.271, -0.053, -0.204]} />
                              </group>
                            </group>
                          </group>
                          <group name="LeftHandRing1" position={[0.015, 0.002, -0.096]} rotation={[0.129, -0.109, 0.117]}>
                            <group name="LeftHandRing2" position={[0, 0, -0.042]} rotation={[0.376, 0.096, 0.015]}>
                              <group name="LeftHandRing3" position={[0, 0, -0.036]} rotation={[0.078, 0.004, 0.011]}>
                                <group name="LeftHandRing4" position={[0, 0, -0.03]} rotation={[0.013, 0.044, 0.014]} />
                              </group>
                            </group>
                          </group>
                          <group name="LeftHandThumb1" position={[-0.032, 0.005, -0.026]} rotation={[0.554, 0.824, -0.241]}>
                            <group name="LeftHandThumb2" position={[0, 0, -0.041]} rotation={[0.118, -0.497, 0.18]}>
                              <group name="LeftHandThumb3" position={[0, 0, -0.03]} rotation={[0.02, -0.169, 0.051]}>
                                <group name="LeftHandThumb4" position={[0, 0, -0.035]} rotation={[0.026, -0.015, -0.105]} />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="Neck" position={[0, 0, -0.156]} rotation={[0.409, 0, 0]}>
                    <group name="Head" position={[0, 0, -0.123]} rotation={[-0.327, 0, 0]}>
                      <group name="HeadTop_End" position={[0, 0.037, -0.226]} rotation={[-0.007, 0, 0]} />
                      <group name="LeftEye" position={[0.03, 0.082, -0.088]} rotation={[-0.007, 0, 0]} />
                      <group name="RightEye" position={[-0.03, 0.082, -0.088]} rotation={[-0.007, 0, 0]} />
                    </group>
                  </group>
                  <group name="RightShoulder" position={[-0.047, -0.006, -0.141]} rotation={[-2.942, 1.526, -1.771]}>
                    <group name="RightArm" position={[0, 0, -0.119]} rotation={[0.999, 0.144, 0.019]}>
                      <group name="RightForeArm" position={[0, 0, -0.285]} rotation={[-0.113, -0.446, 0.021]}>
                        <group name="RightHand" position={[0, 0, -0.252]} rotation={[0.092, 0.041, 0.076]}>
                          <group name="RightHandIndex1" position={[0.035, -0.007, -0.097]} rotation={[0.183, -0.151, -0.09]}>
                            <group name="RightHandIndex2" position={[0, 0, -0.045]} rotation={[0.19, -0.052, -0.007]}>
                              <group name="RightHandIndex3" position={[0, 0, -0.028]} rotation={[0.168, 0.03, -0.155]}>
                                <group name="RightHandIndex4" position={[0, 0, -0.034]} rotation={[0.089, 0.019, 0.113]} />
                              </group>
                            </group>
                          </group>
                          <group name="RightHandMiddle1" position={[0.009, -0.003, -0.1]} rotation={[0.077, -0.036, -0.134]}>
                            <group name="RightHandMiddle2" position={[0, 0, -0.046]} rotation={[0.257, -0.088, -0.008]}>
                              <group name="RightHandMiddle3" position={[0, 0, -0.035]} rotation={[0.408, 0.076, -0.062]}>
                                <group name="RightHandMiddle4" position={[0, 0, -0.035]} rotation={[0.048, 0.004, 0.045]} />
                              </group>
                            </group>
                          </group>
                          <group name="RightHandPinky1" position={[-0.039, 0.011, -0.09]} rotation={[0.209, 0.296, -0.174]}>
                            <group name="RightHandPinky2" position={[0, 0, -0.028]} rotation={[0.229, -0.169, -0.41]}>
                              <group name="RightHandPinky3" position={[0, 0, -0.022]} rotation={[0.246, -0.027, -0.021]}>
                                <group name="RightHandPinky4" position={[0, 0, -0.026]} rotation={[0.271, 0.053, 0.204]} />
                              </group>
                            </group>
                          </group>
                          <group name="RightHandRing1" position={[-0.015, 0.002, -0.096]} rotation={[0.129, 0.109, -0.117]}>
                            <group name="RightHandRing2" position={[0, 0, -0.042]} rotation={[0.376, -0.096, -0.015]}>
                              <group name="RightHandRing3" position={[0, 0, -0.036]} rotation={[0.078, -0.004, -0.011]}>
                                <group name="RightHandRing4" position={[0, 0, -0.03]} rotation={[0.013, -0.044, -0.014]} />
                              </group>
                            </group>
                          </group>
                          <group name="RightHandThumb1" position={[0.032, 0.005, -0.026]} rotation={[0.554, -0.824, 0.241]}>
                            <group name="RightHandThumb2" position={[0, 0, -0.041]} rotation={[0.118, 0.497, -0.18]}>
                              <group name="RightHandThumb3" position={[0, 0, -0.03]} rotation={[0.02, 0.169, -0.051]}>
                                <group name="RightHandThumb4" position={[0, 0, -0.035]} rotation={[0.026, 0.015, 0.105]} />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Armature001" rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials['Wolf3D_Eye.006']} skeleton={nodes.EyeLeft.skeleton} />
          <skinnedMesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials['Wolf3D_Eye.007']} skeleton={nodes.EyeRight.skeleton} />
          <skinnedMesh name="Wolf3D_Body" geometry={nodes.Wolf3D_Body.geometry} material={materials['Wolf3D_Body.003']} skeleton={nodes.Wolf3D_Body.skeleton} />
          <skinnedMesh name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials['Wolf3D_Skin.003']} skeleton={nodes.Wolf3D_Head.skeleton} />
          <skinnedMesh name="Wolf3D_Headwear" geometry={nodes.Wolf3D_Headwear.geometry} material={materials['Wolf3D_Headwear.003']} skeleton={nodes.Wolf3D_Headwear.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Bottom" geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials['Wolf3D_Outfit_Bottom.003']} skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Footwear" geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials['Wolf3D_Outfit_Footwear.003']} skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Top" geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials['Wolf3D_Outfit_Top.003']} skeleton={nodes.Wolf3D_Outfit_Top.skeleton} />
          <skinnedMesh name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials['Wolf3D_Teeth.003']} skeleton={nodes.Wolf3D_Teeth.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/stand.glb')
